#cloud-config
package_update: true

packages:
  - runc

runcmd:
  - curl -sLSf https://github.com/containerd/containerd/releases/download/v1.7.23/containerd-1.7.23-linux-amd64.tar.gz > /tmp/containerd.tar.gz && tar -xvf /tmp/containerd.tar.gz -C /usr/local/bin/ --strip-components=1
  - curl -SLfs https://raw.githubusercontent.com/containerd/containerd/v1.7.23/containerd.service | tee /etc/systemd/system/containerd.service
  - systemctl daemon-reload && systemctl start containerd
  - systemctl enable containerd
  - /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - mkdir -p /opt/cni/bin
  - curl -sSL https://github.com/containernetworking/plugins/releases/download/v1.6.0/cni-plugins-linux-amd64-v1.6.0.tgz | tar -xz -C /opt/cni/bin
  - systemctl status -l containerd --no-pager
